#!/bin/sh

# Copyright 2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRG="$0"
if [ -h "$PRG" ]; then
    PRG=`readlink -f "$PRG"`
fi
PRGDIR=`dirname "$PRG"`

if [ -z "$DUEL_HOME" ]; then
    DUEL_HOME=`cd "$PRGDIR/.." > /dev/null; pwd`
fi

if [ -z "$JAVA_HOME" ]; then
    JAVA_CMD=java
else
    JAVA_CMD="$JAVA_HOME/bin/java"
fi

exec "$JAVA_CMD" \
    $DUEL_OPTIONS \
    -Dduel.home="${DUEL_HOME}" \
    -p "${DUEL_HOME}/lib:${DUEL_HOME}/plugin" \
    -m org.leadpony.duel.cli/org.leadpony.duel.cli.DuelCommand \
    "$@"
